"""
Django settings for FuadFolio project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR,'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production (Render, Railway, ...) set a real SECRET_KEY env var — this
# hardcoded value is only a fallback so local/dev runs work out of the box.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-7w)r1*d=kqo!*5)eu@=x%21(vr9dw@!ty)h*uy7_194@$cx@x7',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Allow all hosts: Replit's preview, Render, and Railway all proxy through
# rotating/dynamic subdomains, so pin down CSRF (below) instead of this.
ALLOWED_HOSTS = ['*']

# Trust known hosting-platform origins for CSRF-protected POST requests (e.g.
# the contact form). Add a comma-separated CSRF_EXTRA_ORIGINS env var (e.g.
# "https://yourdomain.com") for a custom domain on any platform.
CSRF_TRUSTED_ORIGINS = [
    'https://*.replit.dev',
    'https://*.repl.co',
    'https://*.replit.app',
    'https://*.kirk.replit.dev',
    'https://*.picard.replit.dev',
    'https://*.riker.replit.dev',
    'https://*.worf.replit.dev',
    'https://*.janeway.replit.dev',
    'https://*.spock.replit.dev',
    'https://*.sisko.replit.dev',
    'https://*.archer.replit.dev',
    'https://*.onrender.com',
    'https://*.up.railway.app',
    'https://*.railway.app',
]
_extra_origins = os.environ.get('CSRF_EXTRA_ORIGINS', '')
if _extra_origins:
    CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra_origins.split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'about',
    'portfolio',
    'contact',
]

# Public profile info shown across the site (nav, footer, hero, contact).
# GITHUB_USERNAME drives the GitHub-powered "Projects" page: repos are pulled
# live from https://api.github.com/users/<username>/repos, so anything new
# pushed to GitHub shows up automatically without editing the site.
SITE_GITHUB_USERNAME = os.environ.get('SITE_GITHUB_USERNAME', 'alfahim-fuyad')
SITE_EMAIL = os.environ.get('SITE_EMAIL', 'md.alfahim.fuyad@gmail.com')
SITE_LINKEDIN_URL = os.environ.get('SITE_LINKEDIN_URL', 'https://www.linkedin.com/in/al-fahim-36126636b')
SITE_FACEBOOK_URL = os.environ.get('SITE_FACEBOOK_URL', 'https://www.facebook.com/alfahim07')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FuadFolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.site_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'FuadFolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    # Covers Neon (or any managed Postgres) on Replit, Render, or Railway —
    # all of them hand you a single DATABASE_URL connection string. Neon
    # requires SSL, so it's forced on in production; Replit's own dev
    # Postgres doesn't support SSL on its internal network, so DEBUG-mode
    # runs (like this workspace) leave it off.
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ['DATABASE_URL'],
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC_DIR, ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Render and Railway both terminate SSL at their edge and forward requests to
# the app over plain HTTP with an X-Forwarded-Proto header — trust that header
# so Django knows the original request was HTTPS, and harden cookies/redirects
# once we're actually running in production (DEBUG=False).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
