# Generated by Django 6.0.7 on 2026-07-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload the CV/resume PDF served by the Download CV button.', null=True, upload_to='resume/'),
        ),
    ]
