# Generated by Django 6.0.7 on 2026-07-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, help_text='One certification per line. Leave blank to omit this section.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, help_text="One entry per line, e.g. 'Role — Organization (Year–Year): what you did'."),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='Md. Al Fahim Fuyad', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text="One category per line, e.g. 'Languages: Python, SQL, JavaScript'."),
        ),
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, help_text='Short professional summary shown at the top of the generated CV.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, default='Data Scientist | ML Engineer | AI Builder', max_length=160),
        ),
    ]
