# Generated by Django 6.0.7 on 2026-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True, help_text='One achievement per line. Leave blank to omit this section.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='core_competencies',
            field=models.TextField(blank=True, help_text="One competency per line, e.g. 'Machine Learning & Deep Learning'. Leave blank to omit."),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, help_text="Comma or line separated interests, e.g. 'AI Research, Open Source, Problem Solving'."),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.TextField(blank=True, help_text="One per line: 'Language: Level' e.g. 'English: Professional'. Level can be Native/Fluent/Professional/Intermediate/Basic."),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional. Leave blank to omit from the CV.', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='quote',
            field=models.CharField(blank=True, default="Code is like humor. When you have to explain it, it's bad.", help_text='Short quote shown in the CV footer.', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, help_text='Optional personal site/portfolio URL.', max_length=160),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, help_text="Blocks separated by a BLANK LINE. First line of each block: 'Role | Organization | Date range'. Following lines are bullet points. Example:\nAI/ML Engineer (Freelance) | Remote | Jan 2024 – Present\nBuilt and deployed end-to-end ML models and data pipelines.\n\nData Science Intern | ABC Tech Solutions, Dhaka | Jul 2023 – Dec 2023\nAnalyzed large datasets to extract insights."),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text="One category per line, e.g. 'Languages: Python, SQL, JavaScript'. Rendered as pill tags."),
        ),
    ]
